export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILURE = 'SIGN_IN_USER_FAILURE';

export const NAME_REQUEST = 'NAME_REQUEST';
export const NAME_SUCCESS = 'NAME_SUCCESS';
export const NAME_FAILURE = 'NAME_FAILURE';
